_BASE_: "../Base-RCNN-FAN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
#  WEIGHTS: "path/faster_rcnn_r101_3x_fan/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000