_BASE_: "../Base-RCNN-FAN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "/home/cseadmin/huangsh/codes/detectron2/tools/mask_rcnn_r50_1x_fan/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50